#!/usr/bin/env python3
"""Emit backend/db/schema.sql. Feature columns are generated from the
frontend catalogue so the 141 names/order can never drift from features.ts."""
import re, pathlib, sys

ROOT = pathlib.Path("/home/shubham/Desktop/Projects/konsors-sih2")
SRC = ROOT / "react-frontend-test/src/data/features.ts"

rows = []
for ln in SRC.open():
    m = re.match(
        r"\s*\['([A-Z0-9_]+)',\s*'([a-z]+)',\s*'([^']*)',\s*'([^']*)',\s*'([^']*)',\s*"
        r"(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+)(?:,\s*'([a-z]*)')?\]",
        ln,
    )
    if m:
        rows.append(m.groups())

if len(rows) != 141:
    sys.exit(f"expected 141 features, parsed {len(rows)}")

ORDER = ["thermal", "temporal", "spread", "terrain", "fuel", "industry",
         "weather", "smoke", "sar", "chem", "quality"]

cols, comments = [], []
for fam in ORDER:
    fam_rows = [r for r in rows if r[1] == fam]
    cols.append(f"  -- {fam} ({len(fam_rows)})")
    for key, _, label, unit, _src, mu, sd, lo, hi, flags in fam_rows:
        cols.append(f"  {key:<32} double precision,")
        notes = [fam]
        if unit:
            notes.append(f"unit {unit}")
        notes.append(f"reference mean {mu}, sd {sd}, bounds [{lo}, {hi}]")
        if flags:
            if "x" in flags:
                notes.append("stored log1p, display exp(v)-1")
            if "k" in flags:
                notes.append("ALSO FEEDS TRAINING LABELS - disclose in UI")
            if "b" in flags:
                notes.append("binary, no percentile")
        comments.append(
            f"COMMENT ON COLUMN ml.event_feature.{key} IS %s;"
            % ("'" + f"{label} [{fam}] " + "; ".join(notes[1:]) + "'")
        )

# The block is followed by table-level CONSTRAINTs, so every column keeps its
# comma. A comma followed by a "-- family" comment on the next line would be
# swallowed by the comment, which is why the family labels lead the group.
feature_block = "\n".join(cols)
comment_block = "\n".join(comments)

TEMPLATE = r"""-- ============================================================================
-- AGNI-NETRA — PostgreSQL 16 + PostGIS schema
-- Generated by backend/db/generate_schema.py. Do not hand-edit the feature
-- column block; edit the generator or the frontend catalogue instead.
--
--   9 tables · 4 schemas · 5 enums · 4 views
--
-- Companion documents:
--   docs/database-schema.md      the design, and why each table exists
--   docs/database-design-review.md  findings against the submitted diagram
--
-- Apply:  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f backend/db/schema.sql
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS ml;
CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS ops;
CREATE SCHEMA IF NOT EXISTS api;   -- holds only views; no tables

-- ---------------------------------------------------------------------------
-- Enums
--
-- Native enums, not free text. These five vocabularies are frozen by the
-- frontend contract (types.ts:10-16 classes, types.ts:18 statuses, types.ts:335
-- verdicts), so the database should refuse any other value.
--
-- MIGRATION NOTE: adding a value is `ALTER TYPE ... ADD VALUE`, which cannot
-- run inside a transaction block before PG12 and cannot be removed at all.
-- That is the intended trade: a wrong value is impossible, and a new value is
-- an explicit migration.
-- ---------------------------------------------------------------------------

CREATE TYPE core.event_class AS ENUM (
  'wildfire', 'agricultural_burning', 'gas_flare', 'mining', 'industrial', 'unknown'
);

CREATE TYPE core.event_status AS ENUM (
  'abnormal',            -- FRP unusual for THIS location vs its own history
  'routine',             -- normal for this location
  'baseline_building',   -- too little history at this location to judge
  'not_applicable'       -- no meaningful baseline (e.g. vegetation fire)
);

CREATE TYPE core.site_kind AS ENUM (
  'refinery', 'power_plant', 'petrochemical', 'steel', 'cement',
  'mine', 'landfill', 'gas_flare', 'other'
);

CREATE TYPE app.review_verdict AS ENUM ('confirm', 'change', 'false', 'field');

CREATE TYPE ops.job_status AS ENUM ('received', 'running', 'completed', 'partial', 'failed');

-- ---------------------------------------------------------------------------
-- updated_at trigger. Applied to every table so no row can silently lose its
-- audit trail. (Prisma's @updatedAt is client-side only and is not enough.)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION ops.touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

-- ===========================================================================
-- core.site — the only former "Place" row that earns storage
--
-- A curated, monitored heat source with identity and history. NOT a container
-- for events: an event may have no site at all (site_id is nullable), and a
-- site-less event still has a location, because core.event owns that.
--
-- The baseline columns are what make status='abnormal' possible at all:
--   z = (ln(frp) - ln(median_log_frp)) / (1.4826 * mad_log_frp)
-- sd is deliberately NOT stored - it is a constant times mad_log_frp.
-- ===========================================================================

CREATE TABLE core.site (
  id                      bigserial PRIMARY KEY,
  code                    text        NOT NULL UNIQUE,          -- 'GJ-01'
  name                    text        NOT NULL,
  kind                    core.site_kind NOT NULL,
  expected_class          core.event_class NOT NULL,
  source_type             text,

  location                geometry(Point, 4326) NOT NULL,

  -- India has a fixed ~36 states/UTs and ~780 districts, and the polygon
  -- outline layer is already vendored in the frontend (data/geo.ts:9), so
  -- these are indexed text rather than a reference table with geometry.
  state                   text        NOT NULL,
  district                text        NOT NULL,

  -- Rolling baseline over this site's own observation history.
  median_log_frp          numeric(10,6),
  mad_log_frp             numeric(10,6),
  baseline_sample_count   integer     NOT NULL DEFAULT 0,
  baseline_window_days    integer     NOT NULL DEFAULT 365,
  baseline_computed_at    timestamptz,

  coverage                text,                                 -- good | partial | weak
  is_active               boolean     NOT NULL DEFAULT true,
  first_seen_at           timestamptz,
  last_seen_at            timestamptz,

  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT site_mad_nonneg  CHECK (mad_log_frp IS NULL OR mad_log_frp >= 0),
  CONSTRAINT site_samples_nonneg CHECK (baseline_sample_count >= 0)
);

CREATE INDEX site_location_gix ON core.site USING GIST (location);
CREATE INDEX site_state_idx    ON core.site (state, district);
CREATE INDEX site_active_idx   ON core.site (is_active) WHERE is_active;
CREATE TRIGGER site_touch BEFORE UPDATE ON core.site
  FOR EACH ROW EXECUTE FUNCTION ops.touch_updated_at();

COMMENT ON TABLE core.site IS
  'Curated monitored heat sources. Replaces the site half of the old Place table.';
COMMENT ON COLUMN core.site.baseline_sample_count IS
  'Drives status=baseline_building. Derived, never stored on the event.';
COMMENT ON COLUMN core.site.state IS
  'Indexed text, not an FK. See docs/database-schema.md for why.';

-- ===========================================================================
-- core.event — the anchor
--
-- One cluster of detections. It owns the location; there is no second source
-- of truth. Three geometry shapes because three kinds of query need it:
--   centroid  - map viewport + ST_DWithin, single hop, most selective
--   points    - render layer, denormalised cache of core.detection.geom
--   footprint - convex hull, for area and containment
-- core.detection.geom remains the authoritative member points.
-- ===========================================================================

CREATE TABLE core.event (
  id                bigserial PRIMARY KEY,
  -- Idempotency key: a deterministic hash of (source, satellite, acquisition
  -- window, quantised centroid). Re-running ingest must UPSERT on this, never
  -- insert. Without it, re-ingest silently double-counts every baseline.
  ingest_key        text        NOT NULL UNIQUE,

  site_id           bigint      REFERENCES core.site(id) ON DELETE SET NULL,
  merged_into_event_id bigint   REFERENCES core.event(id) ON DELETE SET NULL,

  centroid          geometry(Point, 4326)       NOT NULL,
  points            geometry(MultiPoint, 4326),
  footprint         geometry(MultiPolygon, 4326),

  state             text        NOT NULL,
  district          text        NOT NULL,

  observed_at       timestamptz NOT NULL,
  first_seen_at     timestamptz,
  last_seen_at      timestamptz,
  closed_at         timestamptz,

  frp_median_mw     numeric(12,3),
  frp_p90_mw        numeric(12,3),
  frp_max_mw        numeric(12,3),
  frp_sum_mw        numeric(14,3),
  -- NULL means "no baseline", and must stay distinguishable from 0, which is
  -- a real value meaning "exactly the site median".
  z_score           numeric(7,4),
  area_km2          numeric(12,4),
  detection_count   integer,
  sensor            text,
  local_pass_hour   smallint,

  status            core.event_status NOT NULL DEFAULT 'not_applicable',
  needs_review      boolean     NOT NULL DEFAULT false,

  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT event_frp_nonneg   CHECK (frp_median_mw IS NULL OR frp_median_mw >= 0),
  CONSTRAINT event_area_nonneg  CHECK (area_km2 IS NULL OR area_km2 >= 0),
  CONSTRAINT event_hour_range   CHECK (local_pass_hour IS NULL
                                       OR local_pass_hour BETWEEN 0 AND 23),
  CONSTRAINT event_count_nonneg CHECK (detection_count IS NULL OR detection_count >= 0),
  -- A re-clustered event must not be its own replacement.
  CONSTRAINT event_no_self_merge CHECK (merged_into_event_id IS DISTINCT FROM id)
);

CREATE INDEX event_centroid_gix  ON core.event USING GIST (centroid);
CREATE INDEX event_points_gix    ON core.event USING GIST (points);
CREATE INDEX event_footprint_gix ON core.event USING GIST (footprint);
CREATE INDEX event_observed_idx  ON core.event (observed_at DESC);
CREATE INDEX event_window_idx    ON core.event (state, observed_at DESC);
CREATE INDEX event_status_idx    ON core.event (status, observed_at DESC);
CREATE INDEX event_site_idx      ON core.event (site_id, observed_at DESC);
CREATE INDEX event_review_idx    ON core.event (observed_at DESC) WHERE needs_review;
CREATE INDEX event_live_idx      ON core.event (observed_at DESC)
  WHERE merged_into_event_id IS NULL;   -- the "current" event set
CREATE TRIGGER event_touch BEFORE UPDATE ON core.event
  FOR EACH ROW EXECUTE FUNCTION ops.touch_updated_at();

COMMENT ON COLUMN core.event.ingest_key IS
  'Deterministic cluster identity. Upsert target. Not a surrogate.';
COMMENT ON COLUMN core.event.points IS
  'Denormalised cache of member detections. core.detection.geom is the truth.';

-- ===========================================================================
-- core.detection — one satellite fire pixel
--
-- The raw input, and the time series behind every baseline and every one of
-- the 14 `temporal` features. event_id is NULL until the clusterer runs, so
-- clustering is an UPDATE and re-clustering is expressible as data.
--
-- PARTITIONED monthly on acquisition_time, with a DEFAULT partition so the
-- table is usable before any partition exists.
--
-- Note the primary key: a partitioned table's unique constraints must include
-- the partition key, so it is (id, acquisition_time) and dedupe is
-- (ingest_key, acquisition_time). This is exactly as strong as a global
-- unique on ingest_key alone, because acquisition_time is a component of the
-- hash - the same detection always carries the same timestamp.
-- ===========================================================================

CREATE TABLE core.detection (
  id                bigserial,
  acquisition_time  timestamptz NOT NULL,

  ingest_key        text        NOT NULL,
  -- NULL until clustered. ON DELETE CASCADE is deliberate: deleting an event
  -- returns its detections to the unclustered pool rather than deleting them.
  event_id          bigint      REFERENCES core.event(id) ON DELETE CASCADE,

  source            text        NOT NULL,   -- FIRMS | VIIRS | MODIS
  satellite         text        NOT NULL,
  sensor            text        NOT NULL,

  location          geometry(Point, 4326) NOT NULL,

  frp_mw            numeric(12,3),
  brightness_temp   numeric(6,2),
  confidence        numeric(5,4),
  day_night         char(1),
  cloud_fraction    numeric(5,4),

  ingested_at       timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT detection_pkey PRIMARY KEY (id, acquisition_time),
  CONSTRAINT detection_ingest_uniq UNIQUE (ingest_key, acquisition_time),
  CONSTRAINT detection_conf_range CHECK (confidence IS NULL
                                         OR confidence BETWEEN 0 AND 1),
  CONSTRAINT detection_cloud_range CHECK (cloud_fraction IS NULL
                                          OR cloud_fraction BETWEEN 0 AND 1),
  CONSTRAINT detection_frp_nonneg CHECK (frp_mw IS NULL OR frp_mw >= 0),
  CONSTRAINT detection_daynight   CHECK (day_night IS NULL
                                         OR day_night IN ('D', 'N'))
) PARTITION BY RANGE (acquisition_time);

CREATE TABLE core.detection_default PARTITION OF core.detection DEFAULT;

CREATE INDEX detection_location_gix ON core.detection USING GIST (location);
CREATE INDEX detection_time_brin    ON core.detection USING BRIN (acquisition_time);
CREATE INDEX detection_source_idx   ON core.detection (source, acquisition_time DESC);
CREATE INDEX detection_event_idx    ON core.detection (event_id, acquisition_time DESC);

COMMENT ON TABLE core.detection IS
  'One satellite fire pixel. Raw input; event_id NULL until clustered.';
COMMENT ON COLUMN core.detection.event_id IS
  'Cluster membership. Re-clustering is an UPDATE, plus merged_into_event_id.';

-- ===========================================================================
-- core.event_geometry — plume, spread, footprint layers
--
-- PostGIS, not JSON, so ST_DWithin / ST_Distance / ST_Intersects are ordinary
-- indexed queries. layer is an enum so it is queryable without a scan.
-- ===========================================================================

CREATE TABLE core.event_geometry (
  id              bigserial PRIMARY KEY,
  event_id        bigint      NOT NULL REFERENCES core.event(id) ON DELETE CASCADE,

  layer           text        NOT NULL
    CHECK (layer IN ('plume_core', 'plume_outer', 'plume_trajectory',
                     'spread_ring', 'spread_uncertainty', 'footprint',
                     'detection_hull', 'terrain_profile')),
  horizon_hours   integer,
  geometry        geometry(Geometry, 4326) NOT NULL,

  schema_version  integer     NOT NULL DEFAULT 1,
  computed_at     timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT geometry_horizon_pos CHECK (horizon_hours IS NULL OR horizon_hours > 0)
);

CREATE INDEX geometry_gix    ON core.event_geometry USING GIST (geometry);
CREATE INDEX geometry_event_idx ON core.event_geometry (event_id, layer, horizon_hours);
CREATE UNIQUE INDEX geometry_layer_uniq
  ON core.event_geometry (event_id, layer, horizon_hours, schema_version);

COMMENT ON COLUMN core.event_geometry.layer IS
  'Enum-by-CHECK rather than a PG enum: values are added by the geometry '
  'builders, and CHECK keeps ALTER TYPE out of feature work.';

-- ===========================================================================
-- ml.event_feature — 141 features, keyed (event_id, feature_version)
--
-- All 141 columns nullable, and NULL means "not measured", never 0 - see
-- docs/architecture-flow-diagram.md:107. Many rows per event, so a feature
-- schema bump adds a row instead of overwriting history.
--
-- The model column order is NOT physical column order. It is frozen in code
-- as ml/feature_schema.py::FEATURES and pinned by a contract test against the
-- model artefact and the frontend FDEF catalogue. feature_version records
-- which ordering was used.
-- ===========================================================================

CREATE TABLE ml.event_feature (
  event_id         bigint      NOT NULL REFERENCES core.event(id) ON DELETE CASCADE,
  feature_version  text        NOT NULL,

  missing_fraction numeric(5,4),
  computed_at      timestamptz NOT NULL DEFAULT now(),

__FEATURE_COLUMNS__

  CONSTRAINT event_feature_pkey PRIMARY KEY (event_id, feature_version),
  CONSTRAINT event_feature_missing_range CHECK (missing_fraction IS NULL
                                                OR missing_fraction BETWEEN 0 AND 1)
);

CREATE INDEX event_feature_version_idx ON ml.event_feature (feature_version);
CREATE INDEX event_feature_computed_idx ON ml.event_feature (computed_at DESC);

__FEATURE_COMMENTS__

COMMENT ON TABLE ml.event_feature IS
  '141 model features per event per schema version. NULL = not measured.';
COMMENT ON COLUMN ml.event_feature.missing_fraction IS
  'API response field. Distinct from the MISSING_FEATURE_FRACTION model input.';

-- ===========================================================================
-- ml.prediction — N per event, never columns on core.event
--
-- Every prediction records model_version and feature_version so it is
-- auditable (docs/architecture-flow-diagram.md:106). The model manifest is
-- artifacts/models.json; this table holds the reference and the output.
-- ===========================================================================

CREATE TABLE ml.prediction (
  id                  bigserial PRIMARY KEY,
  event_id            bigint      NOT NULL REFERENCES core.event(id) ON DELETE CASCADE,

  model_version       text        NOT NULL,
  feature_version     text        NOT NULL,

  predicted_at        timestamptz NOT NULL DEFAULT now(),
  predicted_class     core.event_class NOT NULL,
  confidence          numeric(5,4) NOT NULL,
  alt_class           core.event_class,
  alt_probability     numeric(5,4),

  class_probabilities jsonb,
  shap_values         jsonb,
  decision_threshold  numeric(5,4),

  is_current          boolean     NOT NULL DEFAULT true,

  CONSTRAINT prediction_conf_range  CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT prediction_alt_range   CHECK (alt_probability IS NULL
                                           OR alt_probability BETWEEN 0 AND 1),
  -- The runner-up must be labelled whenever it is scored, and vice versa.
  CONSTRAINT prediction_alt_paired  CHECK ((alt_class IS NULL) = (alt_probability IS NULL)),
  CONSTRAINT prediction_threshold   CHECK (decision_threshold IS NULL
                                           OR decision_threshold BETWEEN 0 AND 1)
);

-- At most one current prediction per event.
CREATE UNIQUE INDEX prediction_current_uniq ON ml.prediction (event_id)
  WHERE is_current;
CREATE INDEX prediction_event_idx  ON ml.prediction (event_id, predicted_at DESC);
CREATE INDEX prediction_model_idx  ON ml.prediction (model_version, predicted_at DESC);
CREATE INDEX prediction_class_idx  ON ml.prediction (predicted_class, predicted_at DESC);
-- JSONB containment, for "events where the model was unconfident".
CREATE INDEX prediction_probs_gin ON ml.prediction USING GIN (class_probabilities);

COMMENT ON TABLE ml.prediction IS
  'Versioned predictions. is_current marks the one the API serves.';

-- ===========================================================================
-- app.analyst, app.analyst_review — reviews are labels, so they need a
-- principal and a model anchor.
--
-- The old schema had `reviewer text` and no user table. See
-- docs/frontend-backend-integration-analysis.md:200-201.
-- ===========================================================================

CREATE TABLE app.analyst (
  id            bigserial PRIMARY KEY,
  email         text        NOT NULL UNIQUE,
  display_name  text        NOT NULL,
  role          text        NOT NULL DEFAULT 'analyst'
                CHECK (role IN ('viewer', 'analyst', 'reviewer', 'admin')),
  organisation  text,
  is_active     boolean     NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE app.analyst IS
  'Identity for reviews. The IdP is not modelled here - see open decisions.';

CREATE TABLE app.analyst_review (
  id              bigserial PRIMARY KEY,
  event_id        bigint      NOT NULL REFERENCES core.event(id) ON DELETE CASCADE,
  -- Anchoring to a prediction is what stops the training label rotting when
  -- the model is retrained.
  prediction_id   bigint      NOT NULL REFERENCES ml.prediction(id) ON DELETE RESTRICT,
  analyst_id      bigint      NOT NULL REFERENCES app.analyst(id) ON DELETE RESTRICT,

  verdict         app.review_verdict NOT NULL,
  analyst_class   core.event_class,
  note            text,

  -- Snapshot of the model output at review time, so agreement is computable
  -- later without joining a prediction that may since be superseded.
  model_class_snapshot      core.event_class,
  model_confidence_snapshot numeric(5,4),

  -- Idempotency: a retried POST must not double-insert.
  request_id      text,
  -- An edit supersedes rather than overwrites, so the review history survives.
  superseded_at   timestamptz,

  created_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT review_snapshot_conf CHECK (model_confidence_snapshot IS NULL
                                          OR model_confidence_snapshot BETWEEN 0 AND 1),
  -- analyst_class is required exactly when the analyst changed it.
  CONSTRAINT review_class_paired  CHECK ((analyst_class IS NULL) = (verdict <> 'change')),
  CONSTRAINT review_active        CHECK (superseded_at IS NULL OR superseded_at >= created_at)
);

CREATE UNIQUE INDEX review_request_uniq ON app.analyst_review (request_id)
  WHERE request_id IS NOT NULL;
CREATE INDEX review_event_idx    ON app.analyst_review (event_id, created_at DESC);
CREATE INDEX review_analyst_idx  ON app.analyst_review (analyst_id, created_at DESC);
CREATE INDEX review_prediction_idx ON app.analyst_review (prediction_id);
CREATE INDEX review_verdict_idx  ON app.analyst_review (verdict, created_at DESC);
CREATE INDEX review_training_idx ON app.analyst_review (verdict, analyst_class)
  WHERE superseded_at IS NULL;

COMMENT ON INDEX app.review_training_idx IS
  'Feeds the next training set: live, label-bearing reviews only.';

-- ===========================================================================
-- ops.job — one row per (source, window, stage)
--
-- Absorbs both the ingestion-run record and the per-event processing job.
-- stage = 'ingest' is the run row. This is what /api/metadata/sources reads.
-- ===========================================================================

CREATE TABLE ops.job (
  id              bigserial PRIMARY KEY,

  source          text        NOT NULL,
  window_start    timestamptz,
  window_end      timestamptz,

  stage           text        NOT NULL
    CHECK (stage IN ('ingest', 'cluster', 'features', 'predict', 'geometry')),
  status          ops.job_status NOT NULL DEFAULT 'received',

  event_id        bigint      REFERENCES core.event(id) ON DELETE CASCADE,
  -- Groups the per-event work belonging to one ingest run.
  run_key         text,

  detection_count integer     NOT NULL DEFAULT 0,
  event_count     integer     NOT NULL DEFAULT 0,
  attempt         integer     NOT NULL DEFAULT 1,
  error_message   text,

  started_at      timestamptz,
  completed_at    timestamptz,

  created_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT job_window_ordered CHECK (window_start IS NULL OR window_end IS NULL
                                       OR window_end >= window_start),
  CONSTRAINT job_completed_after CHECK (completed_at IS NULL
                                        OR started_at IS NULL
                                        OR completed_at >= started_at),
  CONSTRAINT job_counts_nonneg CHECK (detection_count >= 0 AND event_count >= 0)
);

CREATE INDEX job_status_idx  ON ops.job (status, created_at DESC);
CREATE INDEX job_stage_idx   ON ops.job (stage, created_at DESC);
CREATE INDEX job_source_idx  ON ops.job (source, window_end DESC);
CREATE INDEX job_run_idx     ON ops.job (run_key) WHERE run_key IS NOT NULL;
CREATE INDEX job_failed_idx  ON ops.job (created_at DESC) WHERE status = 'failed';
-- The freshness query: latest successful ingest per source.
CREATE INDEX job_fresh_idx   ON ops.job (source, window_end DESC)
  WHERE status IN ('completed', 'partial');

COMMENT ON TABLE ops.job IS
  'Ingestion run + processing job in one table. No long job blocks an API call.';

-- ===========================================================================
-- api.* — four views, no storage.
--
-- The frontend's Place object was a stored table. It is a read model, and this
-- is where it lives now. api.v_place reproduces the old payload exactly, so
-- GET /api/places is unchanged and the frontend needs no edit.
-- ===========================================================================

CREATE VIEW api.v_event AS
SELECT e.id,
       e.site_id,
       e.observed_at,
       e.state,
       e.district,
       e.status,
       e.z_score,
       e.frp_median_mw,
       e.frp_max_mw,
       e.area_km2,
       e.detection_count,
       e.sensor,
       e.local_pass_hour,
       e.needs_review,
       e.merged_into_event_id,
       ST_X(e.centroid) AS lon,
       ST_Y(e.centroid) AS lat,
       p.predicted_class,
       p.confidence,
       p.alt_class,
       p.alt_probability,
       p.model_version,
       p.feature_version
FROM core.event e
LEFT JOIN ml.prediction p ON p.event_id = e.id AND p.is_current
WHERE e.merged_into_event_id IS NULL;   -- current set only

COMMENT ON VIEW api.v_event IS
  'Event + its current prediction. Coordinates are [lon, lat] per types.ts:7.';

CREATE VIEW api.v_place AS
-- The curated sites...
SELECT s.id::text                          AS id,
       'site'::text                        AS kind,
       s.code,
       s.name,
       s.state,
       s.district,
       ST_Y(s.location)                    AS lat,
       ST_X(s.location)                    AS lon,
       s.expected_class                    AS class,
       s.kind::text                        AS type,
       exp(s.median_log_frp)::double precision AS median_frp_mw,
       s.mad_log_frp::double precision     AS mad,
       s.coverage,
       s.first_seen_at
FROM core.site s
WHERE s.is_active
UNION ALL
-- ...and the events that have no site, labelled at query time instead of
-- stored. This is the 280 synthetic "transient" Place rows, now 0 rows.
SELECT 'e' || e.id::text                    AS id,
       'transient'::text                   AS kind,
       NULL::text                          AS code,
       COALESCE(c.label || ' near ' || e.district, e.district) AS name,
       e.state,
       e.district,
       ST_Y(e.centroid)                    AS lat,
       ST_X(e.centroid)                    AS lon,
       p.predicted_class                   AS class,
       CASE WHEN p.predicted_class = 'wildfire' THEN 'Vegetation fire'
            WHEN p.predicted_class = 'agricultural_burning' THEN 'Crop residue fire'
            ELSE 'Unclassified heat' END   AS type,
       e.frp_median_mw::double precision   AS median_frp_mw,
       NULL::double precision              AS mad,
       NULL::text                          AS coverage,
       e.observed_at                       AS first_seen_at
FROM core.event e
LEFT JOIN ml.prediction p ON p.event_id = e.id AND p.is_current
LEFT JOIN LATERAL (
  -- Nearest curated site within ~16 km, for a human-readable label. The
  -- radius stops a Kerala fire being labelled "near Jamnagar refinery".
  SELECT s.name AS label
  FROM core.site s
  WHERE s.is_active
    AND ST_DWithin(s.location, e.centroid, 0.15)
  ORDER BY s.location <-> e.centroid
  LIMIT 1
) c ON true
WHERE e.merged_into_event_id IS NULL
  AND e.observed_at >= now() - interval '90 days'
  AND e.site_id IS NULL;

COMMENT ON VIEW api.v_place IS
  'Reproduces the old Place payload. Sites UNION derived event anchors.';

CREATE VIEW api.v_place_history AS
-- The per-site series behind the timeline, the baseline and the z-scores.
-- Built from detections rather than a stored observation table, so the
-- baseline is always recomputable from raw input.
SELECT e.site_id,
       d.acquisition_time                         AS observed_at,
       SUM(d.frp_mw)                              AS frp_mw_sum,
       COUNT(*)                                   AS detection_count,
       max(d.sensor)                              AS sensor,
       CASE
         WHEN s.baseline_sample_count = 0 THEN NULL
         WHEN s.mad_log_frp IS NULL OR s.mad_log_frp = 0 THEN NULL
         ELSE round((ln(sum(d.frp_mw))
                     - s.median_log_frp) / (1.4826 * s.mad_log_frp), 4)
       END                                        AS z_score
FROM core.detection d
JOIN core.event e ON e.id = d.event_id
LEFT JOIN core.site s ON s.id = e.site_id
WHERE e.site_id IS NOT NULL
GROUP BY e.site_id, d.acquisition_time, s.median_log_frp,
         s.mad_log_frp, s.baseline_sample_count;

COMMENT ON VIEW api.v_place_history IS
  'observations[] for GET /api/places/{id}/history. Gaps are generated by '
  'date_series() in the query, not stored.';

CREATE VIEW api.v_source_freshness AS
-- Backs GET /api/metadata/sources. age is computed, never stored, so it
-- cannot go stale in the row it describes.
SELECT j.source,
       max(j.window_end)                        AS last_window_end,
       max(j.completed_at)                      AS last_completed_at,
       now() - max(j.completed_at)              AS age,
       CASE
         WHEN max(j.completed_at) IS NULL THEN 'never'
         WHEN now() - max(j.completed_at) > interval '6 hours' THEN 'stale'
         ELSE 'ok'
       END                                      AS status,
       sum(j.detection_count) FILTER (WHERE j.stage = 'ingest'
                                       AND j.status = 'completed') AS detections_ingested,
       count(*) FILTER (WHERE j.status = 'failed')                AS failed_jobs,
       count(*) FILTER (WHERE j.status = 'partial')               AS partial_jobs
FROM ops.job j
GROUP BY j.source;

COMMENT ON VIEW api.v_source_freshness IS
  'Source age and ingestion health. Recomputed on read, never cached.';

-- ===========================================================================
-- Housekeeping
-- ===========================================================================

-- Monthly partitions. The DEFAULT partition above catches anything outside
-- these ranges, so this is safe to run on an empty table and easy to extend.
--   SELECT create_detections_partition('2026-10');   -- 'YYYY-MM'
--
-- IMPORTANT: once a month has accumulated rows in detection_default, creating
-- that month as a real partition requires a full scan of the default to prove
-- no row belongs in the new partition. Detach the month first:
--   CREATE TABLE core.detections_2026_10_stage PARTITION OF core.detection_default
--     FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
--   DELETE FROM core.detection_default WHERE ...;  -- then drop the stage table
--
-- Retention: detach and archive whole partitions, do not DELETE row by row.
-- ===========================================================================

CREATE OR REPLACE FUNCTION create_detections_partition(month text)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE
  start  date;
  finish date;
  name   text;
BEGIN
  -- Accepts 'YYYY-MM' or any date castable to YYYY-MM.
  start  := date_trunc('month',
              CASE WHEN month ~ '^[0-9]{4}-[0-9]{2}$'
                   THEN to_date(month || '-01', 'YYYY-MM-DD')
                   ELSE month::date END)::date;
  finish := (start + interval '1 month')::date;
  name   := 'detections_' || to_char(start, 'YYYY_MM');

  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS core.%I PARTITION OF core.detection '
    'FOR VALUES FROM (%L) TO (%L)', name, start, finish);
  RETURN 'core.' || name;
END $$;

-- Overload so DATE '2026-10-01' also works without a cast at the call site.
CREATE OR REPLACE FUNCTION create_detections_partition(month date)
RETURNS text LANGUAGE sql AS
$$ SELECT create_detections_partition(to_char($1, 'YYYY-MM')) $$;"""

out = TEMPLATE.replace("__FEATURE_COLUMNS__", feature_block) \
               .replace("__FEATURE_COMMENTS__", comment_block)
(ROOT / "backend/db/schema.sql").write_text(out.rstrip("\n") + "\n")
print(f"wrote backend/db/schema.sql  ({len(out.splitlines())} lines, "
      f"{len(rows)} feature columns, {len(comments)} column comments)")
